site_name: AIOT开放平台文档中心
site_author: AIOT Open Cloud Group
site_url: https://docs.opencloud.aqara.cn/
repo_url: https://github.com/aqara/opencloud-docs/
copyright: Copyright 2016-2017, aqara.cn, All Rights Reserved. <br />粤ICP备15041247号-13 深圳绿米联创科技有限公司
docs_dir: zh

pages:
- 简介: index.md
- 新手帮助: 
  - 产品介绍: guideline/product-discription.md
  - 账号与密码: guideline/account-and-password.md
- 开发手册:
  - 云端开发手册: development/cloud-development.md
  - 网关局域网通讯协议: blank.md
- 部署与运维:
  - 安装配置指南: blank.md
  - 故障诊断指南: blank.md
- 常见问题: blank.md
